options:
  cluster_id:
    type: string
    default: 'drill-cluster'
    description: 'Cluster ID for zookeeper'
  drill_max_direct_memory:
     type: string
     default: '75%'
     description: 'Drill Max Available RAM. By default we set this to 75% of total system ram. You can provide a percentage value or a Gigabyte value like: 8G'
  drill_heap:
      type: string
      default: '25%'
      description: 'Drill Max Heap Size. By default we set this to 25% of total system ram. You can provide a percentage value or a Gigabyte value like: 3G'
  hdfs_path:
      type: string
      default: '/user/ubuntu'
      description: 'Default path for HDFS connections.'
  hdfs_writeable:
      type: boolean
      default: True
      description: 'Is the HDFS path writable?'
  hdfs_formats:
      type: string
      default:'            "psv": {
                              "type": "text",
                              "extensions": [
                                  "tbl"
                              ],
                              "delimiter": "|"
                          },
                          "csv": {
                              "type": "text",
                              "extensions": [
                                  "csv"
                              ],
                              "delimiter": ","
                          },
                          "tsv": {
                              "type": "text",
                              "extensions": [
                                  "tsv"
                              ],
                              "delimiter": "\t"
                          },
                          "parquet": {
                              "type": "parquet"
                          },
                          "json": {
                              "type": "json",
                              "extensions": [
                                  "json"
                              ]
                          },
                          "avro": {
                              "type": "avro"
                          },
                          "sequencefile": {
                              "type": "sequencefile",
                              "extensions": [
                                  "seq"
                              ]
                          },
                          "csvh": {
                              "type": "text",
                              "extensions": [
                                  "csvh"
                              ],
                              "extractHeader": True,
                              "delimiter": ","
                          }'
